from selenium.webdriver.common.by import By


class LocatorMainYaScooterPage:
    YANDEX_BUTTON = (By.XPATH, "//img[@alt='Yandex']")
    SCOOTER_BUTTON = (By.XPATH, "//img[@alt='Scooter']")
    ORDER_BUTTON_IN_HEADER = (By.XPATH, "//div[contains(@class,'Header_Nav')]/button[contains(@class,'Button_Button')]")
    ORDER_BUTTON_IN_MIDDLE = (By.XPATH, "//button[contains(@class,'Button_Middle')]")
    QUESTION_ONE = (By.ID, "accordion__heading-0")
    ANSWER_ONE = (By.XPATH, "//div[@id='accordion__panel-0']/p")
    QUESTION_TWO = (By.ID, "accordion__heading-1")
    ANSWER_TWO = (By.XPATH, "//div[@id='accordion__panel-1']/p")
    QUESTION_THRE = (By.ID, "accordion__heading-2")
    ANSWER_THREE = (By.XPATH, "//div[@id='accordion__panel-2']/p")
    QUESTION_FOUR = (By.ID, "accordion__heading-3")
    ANSWER_FOUR = (By.XPATH, "//div[@id='accordion__panel-3']/p")
    QUESTION_FIVE = (By.ID, "accordion__heading-4")
    ANSWER_FIVE = (By.XPATH, "//div[@id='accordion__panel-4']/p")
    QUESTION_SIX = (By.ID, "accordion__heading-5")
    ANSWER_SIX = (By.XPATH, "//div[@id='accordion__panel-5']/p")
    QUESTION_SEVEN = (By.ID, "accordion__heading-6")
    ANSWER_SEVEN = (By.XPATH, "//div[@id='accordion__panel-6']/p")
    QUESTION_EIGHT = (By.ID, "accordion__heading-7")
    ANSWER_EIGHT = (By.XPATH, "//div[@id='accordion__panel-7']/p")
    BLOCK_WITH_QUESTIONS = (By.XPATH, "//div[contains(text(),'Вопросы о важном')]")
